<?xml version="1.0" encoding="UTF-8"?>
<!--
This file was generated by Altova MapForce 2015r4

YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.

Refer to the Altova MapForce Documentation for further details.
http://www.altova.com/mapforce
-->
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:agt="http://www.altova.com/Mapforce/agt" xmlns:xs="http://www.w3.org/2001/XMLSchema" exclude-result-prefixes="agt xs">
	<xsl:output method="xml" encoding="UTF-8" indent="yes"/>
	<xsl:template name="agt:MapToCanLocARA_A_Cede_var130_function">
		<xsl:param name="var129_current"/>
		<xsl:variable name="var125_LocationPerilWind">
			<xsl:if test="$var129_current/@LocationPerilWind">
				<xsl:value-of select="'1'"/>
			</xsl:if>
		</xsl:variable>
		<xsl:variable name="var126_resultof_exists" select="boolean(string($var125_LocationPerilWind))"/>
		<xsl:variable name="var127_LocationPerilSurge">
			<xsl:if test="$var129_current/@LocationPerilSurge">
				<xsl:value-of select="'1'"/>
			</xsl:if>
		</xsl:variable>
		<xsl:variable name="var128_resultof_exists" select="boolean(string($var127_LocationPerilSurge))"/>
		<rec>
			<xsl:variable name="var1_ContractSID">
				<xsl:if test="$var129_current/@ContractSID">
					<xsl:value-of select="'1'"/>
				</xsl:if>
			</xsl:variable>
			<xsl:if test="string(boolean(string($var1_ContractSID))) != 'false'">
				<xsl:attribute name="ContractSID">
					<xsl:value-of select="string($var129_current/@ContractSID)"/>
				</xsl:attribute>
			</xsl:if>
			<xsl:variable name="var2_ContractID">
				<xsl:if test="$var129_current/@ContractID">
					<xsl:value-of select="'1'"/>
				</xsl:if>
			</xsl:variable>
			<xsl:if test="string(boolean(string($var2_ContractID))) != 'false'">
				<xsl:attribute name="ContractID">
					<xsl:value-of select="string($var129_current/@ContractID)"/>
				</xsl:attribute>
			</xsl:if>
			<xsl:variable name="var3_ExposureSetSID">
				<xsl:if test="$var129_current/@ExposureSetSID">
					<xsl:value-of select="'1'"/>
				</xsl:if>
			</xsl:variable>
			<xsl:if test="string(boolean(string($var3_ExposureSetSID))) != 'false'">
				<xsl:attribute name="ExposureSetSID">
					<xsl:value-of select="string($var129_current/@ExposureSetSID)"/>
				</xsl:attribute>
			</xsl:if>
			<xsl:variable name="var4_LocationSID">
				<xsl:if test="$var129_current/@LocationSID">
					<xsl:value-of select="'1'"/>
				</xsl:if>
			</xsl:variable>
			<xsl:if test="string(boolean(string($var4_LocationSID))) != 'false'">
				<xsl:attribute name="LocationSID">
					<xsl:value-of select="string($var129_current/@LocationSID)"/>
				</xsl:attribute>
			</xsl:if>
			<xsl:variable name="var5_LocationID">
				<xsl:if test="$var129_current/@LocationID">
					<xsl:value-of select="'1'"/>
				</xsl:if>
			</xsl:variable>
			<xsl:if test="string(boolean(string($var5_LocationID))) != 'false'">
				<xsl:attribute name="LocationID">
					<xsl:value-of select="string($var129_current/@LocationID)"/>
				</xsl:attribute>
			</xsl:if>
			<xsl:variable name="var6_LocationName">
				<xsl:if test="$var129_current/@LocationName">
					<xsl:value-of select="'1'"/>
				</xsl:if>
			</xsl:variable>
			<xsl:if test="string(boolean(string($var6_LocationName))) != 'false'">
				<xsl:attribute name="LocationName">
					<xsl:value-of select="string($var129_current/@LocationName)"/>
				</xsl:attribute>
			</xsl:if>
			<xsl:variable name="var7_PostalCode">
				<xsl:if test="$var129_current/@PostalCode">
					<xsl:value-of select="'1'"/>
				</xsl:if>
			</xsl:variable>
			<xsl:if test="string(boolean(string($var7_PostalCode))) != 'false'">
				<xsl:attribute name="PostalCode">
					<xsl:value-of select="string($var129_current/@PostalCode)"/>
				</xsl:attribute>
			</xsl:if>
			<xsl:variable name="var8_CountryCode">
				<xsl:if test="$var129_current/@CountryCode">
					<xsl:value-of select="'1'"/>
				</xsl:if>
			</xsl:variable>
			<xsl:if test="string(boolean(string($var8_CountryCode))) != 'false'">
				<xsl:attribute name="CountryCode">
					<xsl:value-of select="string($var129_current/@CountryCode)"/>
				</xsl:attribute>
			</xsl:if>
			<xsl:variable name="var9_AreaCode">
				<xsl:if test="$var129_current/@AreaCode">
					<xsl:value-of select="'1'"/>
				</xsl:if>
			</xsl:variable>
			<xsl:if test="string(boolean(string($var9_AreaCode))) != 'false'">
				<xsl:attribute name="AreaCode">
					<xsl:value-of select="string($var129_current/@AreaCode)"/>
				</xsl:attribute>
			</xsl:if>
			<xsl:variable name="var10_SubareaCode">
				<xsl:if test="$var129_current/@SubareaCode">
					<xsl:value-of select="'1'"/>
				</xsl:if>
			</xsl:variable>
			<xsl:if test="string(boolean(string($var10_SubareaCode))) != 'false'">
				<xsl:attribute name="SubareaCode">
					<xsl:value-of select="string($var129_current/@SubareaCode)"/>
				</xsl:attribute>
			</xsl:if>
			<xsl:variable name="var11_Latitude">
				<xsl:if test="$var129_current/@Latitude">
					<xsl:value-of select="'1'"/>
				</xsl:if>
			</xsl:variable>
			<xsl:if test="string(boolean(string($var11_Latitude))) != 'false'">
				<xsl:attribute name="Latitude">
					<xsl:value-of select="string($var129_current/@Latitude)"/>
				</xsl:attribute>
			</xsl:if>
			<xsl:variable name="var12_Longitude">
				<xsl:if test="$var129_current/@Longitude">
					<xsl:value-of select="'1'"/>
				</xsl:if>
			</xsl:variable>
			<xsl:if test="string(boolean(string($var12_Longitude))) != 'false'">
				<xsl:attribute name="Longitude">
					<xsl:value-of select="string($var129_current/@Longitude)"/>
				</xsl:attribute>
			</xsl:if>
			<xsl:variable name="var13_AIRConstructionCodeA">
				<xsl:if test="$var129_current/@AIRConstructionCodeA">
					<xsl:value-of select="'1'"/>
				</xsl:if>
			</xsl:variable>
			<xsl:if test="string(boolean(string($var13_AIRConstructionCodeA))) != 'false'">
				<xsl:attribute name="AIRConstructionCodeA">
					<xsl:value-of select="string($var129_current/@AIRConstructionCodeA)"/>
				</xsl:attribute>
			</xsl:if>
			<xsl:variable name="var14_AIRConstructionCodeB">
				<xsl:if test="$var129_current/@AIRConstructionCodeB">
					<xsl:value-of select="'1'"/>
				</xsl:if>
			</xsl:variable>
			<xsl:if test="string(boolean(string($var14_AIRConstructionCodeB))) != 'false'">
				<xsl:attribute name="AIRConstructionCodeB">
					<xsl:value-of select="string($var129_current/@AIRConstructionCodeB)"/>
				</xsl:attribute>
			</xsl:if>
			<xsl:variable name="var15_AIROccupancyCode">
				<xsl:if test="$var129_current/@AIROccupancyCode">
					<xsl:value-of select="'1'"/>
				</xsl:if>
			</xsl:variable>
			<xsl:if test="string(boolean(string($var15_AIROccupancyCode))) != 'false'">
				<xsl:attribute name="AIROccupancyCode">
					<xsl:value-of select="string($var129_current/@AIROccupancyCode)"/>
				</xsl:attribute>
			</xsl:if>
			<xsl:variable name="var16_YearBuilt">
				<xsl:if test="$var129_current/@YearBuilt">
					<xsl:value-of select="'1'"/>
				</xsl:if>
			</xsl:variable>
			<xsl:if test="string(boolean(string($var16_YearBuilt))) != 'false'">
				<xsl:attribute name="YearBuilt">
					<xsl:value-of select="string($var129_current/@YearBuilt)"/>
				</xsl:attribute>
			</xsl:if>
			<xsl:variable name="var17_Stories">
				<xsl:if test="$var129_current/@Stories">
					<xsl:value-of select="'1'"/>
				</xsl:if>
			</xsl:variable>
			<xsl:if test="string(boolean(string($var17_Stories))) != 'false'">
				<xsl:attribute name="Stories">
					<xsl:value-of select="string($var129_current/@Stories)"/>
				</xsl:attribute>
			</xsl:if>
			<xsl:variable name="var18_RiskCount">
				<xsl:if test="$var129_current/@RiskCount">
					<xsl:value-of select="'1'"/>
				</xsl:if>
			</xsl:variable>
			<xsl:if test="string(boolean(string($var18_RiskCount))) != 'false'">
				<xsl:attribute name="RiskCount">
					<xsl:value-of select="string($var129_current/@RiskCount)"/>
				</xsl:attribute>
			</xsl:if>
			<xsl:variable name="var19_GrossArea">
				<xsl:if test="$var129_current/@GrossArea">
					<xsl:value-of select="'1'"/>
				</xsl:if>
			</xsl:variable>
			<xsl:if test="string(boolean(string($var19_GrossArea))) != 'false'">
				<xsl:attribute name="GrossArea">
					<xsl:value-of select="string($var129_current/@GrossArea)"/>
				</xsl:attribute>
			</xsl:if>
			<xsl:variable name="var20_LocationCurrency">
				<xsl:if test="$var129_current/@LocationCurrency">
					<xsl:value-of select="'1'"/>
				</xsl:if>
			</xsl:variable>
			<xsl:if test="string(boolean(string($var20_LocationCurrency))) != 'false'">
				<xsl:attribute name="LocationCurrency">
					<xsl:value-of select="string($var129_current/@LocationCurrency)"/>
				</xsl:attribute>
			</xsl:if>
			<xsl:variable name="var22_resultof_logical_and" select="(('1' = string($var129_current/@LocationPerilWind)) and (string($var129_current/@LocationPerilSurge) = '0'))"/>
			<xsl:variable name="var21_ReplacementValueA">
				<xsl:if test="$var129_current/@ReplacementValueA">
					<xsl:value-of select="'1'"/>
				</xsl:if>
			</xsl:variable>
			<xsl:if test="string($var126_resultof_exists) != 'false'">
				<xsl:if test="string($var128_resultof_exists) != 'false'">
					<xsl:if test="string((not($var22_resultof_logical_and) or boolean(string($var21_ReplacementValueA)))) != 'false'">
						<xsl:attribute name="ReplacementValueA_W">
							<xsl:choose>
								<xsl:when test="string($var22_resultof_logical_and) != 'false'">
									<xsl:value-of select="string($var129_current/@ReplacementValueA)"/>
								</xsl:when>
								<xsl:otherwise>
									<xsl:value-of select="'0'"/>
								</xsl:otherwise>
							</xsl:choose>
						</xsl:attribute>
					</xsl:if>
				</xsl:if>
			</xsl:if>
			<xsl:variable name="var24_resultof_logical_and" select="(('1' = string($var129_current/@LocationPerilWind)) and (string($var129_current/@LocationPerilSurge) = '0'))"/>
			<xsl:variable name="var23_ReplacementValueB">
				<xsl:if test="$var129_current/@ReplacementValueB">
					<xsl:value-of select="'1'"/>
				</xsl:if>
			</xsl:variable>
			<xsl:if test="string($var126_resultof_exists) != 'false'">
				<xsl:if test="string($var128_resultof_exists) != 'false'">
					<xsl:if test="string((not($var24_resultof_logical_and) or boolean(string($var23_ReplacementValueB)))) != 'false'">
						<xsl:attribute name="ReplacementValueB_W">
							<xsl:choose>
								<xsl:when test="string($var24_resultof_logical_and) != 'false'">
									<xsl:value-of select="string($var129_current/@ReplacementValueB)"/>
								</xsl:when>
								<xsl:otherwise>
									<xsl:value-of select="'0'"/>
								</xsl:otherwise>
							</xsl:choose>
						</xsl:attribute>
					</xsl:if>
				</xsl:if>
			</xsl:if>
			<xsl:variable name="var26_resultof_logical_and" select="(('1' = string($var129_current/@LocationPerilWind)) and (string($var129_current/@LocationPerilSurge) = '0'))"/>
			<xsl:variable name="var25_ReplacementValueC">
				<xsl:if test="$var129_current/@ReplacementValueC">
					<xsl:value-of select="'1'"/>
				</xsl:if>
			</xsl:variable>
			<xsl:if test="string($var126_resultof_exists) != 'false'">
				<xsl:if test="string($var128_resultof_exists) != 'false'">
					<xsl:if test="string((not($var26_resultof_logical_and) or boolean(string($var25_ReplacementValueC)))) != 'false'">
						<xsl:attribute name="ReplacementValueC_W">
							<xsl:choose>
								<xsl:when test="string($var26_resultof_logical_and) != 'false'">
									<xsl:value-of select="string($var129_current/@ReplacementValueC)"/>
								</xsl:when>
								<xsl:otherwise>
									<xsl:value-of select="'0'"/>
								</xsl:otherwise>
							</xsl:choose>
						</xsl:attribute>
					</xsl:if>
				</xsl:if>
			</xsl:if>
			<xsl:variable name="var28_resultof_logical_and" select="(('1' = string($var129_current/@LocationPerilWind)) and (string($var129_current/@LocationPerilSurge) = '0'))"/>
			<xsl:variable name="var27_ReplacementValueD">
				<xsl:if test="$var129_current/@ReplacementValueD">
					<xsl:value-of select="'1'"/>
				</xsl:if>
			</xsl:variable>
			<xsl:if test="string($var126_resultof_exists) != 'false'">
				<xsl:if test="string($var128_resultof_exists) != 'false'">
					<xsl:if test="string((not($var28_resultof_logical_and) or boolean(string($var27_ReplacementValueD)))) != 'false'">
						<xsl:attribute name="ReplacementValueD_W">
							<xsl:choose>
								<xsl:when test="string($var28_resultof_logical_and) != 'false'">
									<xsl:value-of select="string($var129_current/@ReplacementValueD)"/>
								</xsl:when>
								<xsl:otherwise>
									<xsl:value-of select="'0'"/>
								</xsl:otherwise>
							</xsl:choose>
						</xsl:attribute>
					</xsl:if>
				</xsl:if>
			</xsl:if>
			<xsl:variable name="var30_resultof_logical_and" select="((string($var129_current/@LocationPerilWind) = '0') and (string($var129_current/@LocationPerilSurge) = '1'))"/>
			<xsl:variable name="var29_ReplacementValueA">
				<xsl:if test="$var129_current/@ReplacementValueA">
					<xsl:value-of select="'1'"/>
				</xsl:if>
			</xsl:variable>
			<xsl:if test="string($var126_resultof_exists) != 'false'">
				<xsl:if test="string($var128_resultof_exists) != 'false'">
					<xsl:if test="string((not($var30_resultof_logical_and) or boolean(string($var29_ReplacementValueA)))) != 'false'">
						<xsl:attribute name="ReplacementValueA_S">
							<xsl:choose>
								<xsl:when test="string($var30_resultof_logical_and) != 'false'">
									<xsl:value-of select="string($var129_current/@ReplacementValueA)"/>
								</xsl:when>
								<xsl:otherwise>
									<xsl:value-of select="'0'"/>
								</xsl:otherwise>
							</xsl:choose>
						</xsl:attribute>
					</xsl:if>
				</xsl:if>
			</xsl:if>
			<xsl:variable name="var32_resultof_logical_and" select="((string($var129_current/@LocationPerilWind) = '0') and (string($var129_current/@LocationPerilSurge) = '1'))"/>
			<xsl:variable name="var31_ReplacementValueB">
				<xsl:if test="$var129_current/@ReplacementValueB">
					<xsl:value-of select="'1'"/>
				</xsl:if>
			</xsl:variable>
			<xsl:if test="string($var126_resultof_exists) != 'false'">
				<xsl:if test="string($var128_resultof_exists) != 'false'">
					<xsl:if test="string((not($var32_resultof_logical_and) or boolean(string($var31_ReplacementValueB)))) != 'false'">
						<xsl:attribute name="ReplacementValueB_S">
							<xsl:choose>
								<xsl:when test="string($var32_resultof_logical_and) != 'false'">
									<xsl:value-of select="string($var129_current/@ReplacementValueB)"/>
								</xsl:when>
								<xsl:otherwise>
									<xsl:value-of select="'0'"/>
								</xsl:otherwise>
							</xsl:choose>
						</xsl:attribute>
					</xsl:if>
				</xsl:if>
			</xsl:if>
			<xsl:variable name="var34_resultof_logical_and" select="((string($var129_current/@LocationPerilWind) = '0') and (string($var129_current/@LocationPerilSurge) = '1'))"/>
			<xsl:variable name="var33_ReplacementValueC">
				<xsl:if test="$var129_current/@ReplacementValueC">
					<xsl:value-of select="'1'"/>
				</xsl:if>
			</xsl:variable>
			<xsl:if test="string($var126_resultof_exists) != 'false'">
				<xsl:if test="string($var128_resultof_exists) != 'false'">
					<xsl:if test="string((not($var34_resultof_logical_and) or boolean(string($var33_ReplacementValueC)))) != 'false'">
						<xsl:attribute name="ReplacementValueC_S">
							<xsl:choose>
								<xsl:when test="string($var34_resultof_logical_and) != 'false'">
									<xsl:value-of select="string($var129_current/@ReplacementValueC)"/>
								</xsl:when>
								<xsl:otherwise>
									<xsl:value-of select="'0'"/>
								</xsl:otherwise>
							</xsl:choose>
						</xsl:attribute>
					</xsl:if>
				</xsl:if>
			</xsl:if>
			<xsl:variable name="var36_resultof_logical_and" select="((string($var129_current/@LocationPerilWind) = '0') and (string($var129_current/@LocationPerilSurge) = '1'))"/>
			<xsl:variable name="var35_ReplacementValueC">
				<xsl:if test="$var129_current/@ReplacementValueC">
					<xsl:value-of select="'1'"/>
				</xsl:if>
			</xsl:variable>
			<xsl:if test="string($var126_resultof_exists) != 'false'">
				<xsl:if test="string($var128_resultof_exists) != 'false'">
					<xsl:if test="string((not($var36_resultof_logical_and) or boolean(string($var35_ReplacementValueC)))) != 'false'">
						<xsl:attribute name="ReplacementValueD_S">
							<xsl:choose>
								<xsl:when test="string($var36_resultof_logical_and) != 'false'">
									<xsl:value-of select="string($var129_current/@ReplacementValueC)"/>
								</xsl:when>
								<xsl:otherwise>
									<xsl:value-of select="'0'"/>
								</xsl:otherwise>
							</xsl:choose>
						</xsl:attribute>
					</xsl:if>
				</xsl:if>
			</xsl:if>
			<xsl:variable name="var38_resultof_logical_and" select="((string($var129_current/@LocationPerilWind) = '1') and (string($var129_current/@LocationPerilSurge) = '1'))"/>
			<xsl:variable name="var37_ReplacementValueA">
				<xsl:if test="$var129_current/@ReplacementValueA">
					<xsl:value-of select="'1'"/>
				</xsl:if>
			</xsl:variable>
			<xsl:if test="string($var126_resultof_exists) != 'false'">
				<xsl:if test="string($var128_resultof_exists) != 'false'">
					<xsl:if test="string((not($var38_resultof_logical_and) or boolean(string($var37_ReplacementValueA)))) != 'false'">
						<xsl:attribute name="ReplacementValueA_WS">
							<xsl:choose>
								<xsl:when test="string($var38_resultof_logical_and) != 'false'">
									<xsl:value-of select="string($var129_current/@ReplacementValueA)"/>
								</xsl:when>
								<xsl:otherwise>
									<xsl:value-of select="'0'"/>
								</xsl:otherwise>
							</xsl:choose>
						</xsl:attribute>
					</xsl:if>
				</xsl:if>
			</xsl:if>
			<xsl:variable name="var40_resultof_logical_and" select="((string($var129_current/@LocationPerilWind) = '1') and (string($var129_current/@LocationPerilSurge) = '1'))"/>
			<xsl:variable name="var39_ReplacementValueB">
				<xsl:if test="$var129_current/@ReplacementValueB">
					<xsl:value-of select="'1'"/>
				</xsl:if>
			</xsl:variable>
			<xsl:if test="string($var126_resultof_exists) != 'false'">
				<xsl:if test="string($var128_resultof_exists) != 'false'">
					<xsl:if test="string((not($var40_resultof_logical_and) or boolean(string($var39_ReplacementValueB)))) != 'false'">
						<xsl:attribute name="ReplacementValueB_WS">
							<xsl:choose>
								<xsl:when test="string($var40_resultof_logical_and) != 'false'">
									<xsl:value-of select="string($var129_current/@ReplacementValueB)"/>
								</xsl:when>
								<xsl:otherwise>
									<xsl:value-of select="'0'"/>
								</xsl:otherwise>
							</xsl:choose>
						</xsl:attribute>
					</xsl:if>
				</xsl:if>
			</xsl:if>
			<xsl:variable name="var42_resultof_logical_and" select="((string($var129_current/@LocationPerilWind) = '1') and (string($var129_current/@LocationPerilSurge) = '1'))"/>
			<xsl:variable name="var41_ReplacementValueC">
				<xsl:if test="$var129_current/@ReplacementValueC">
					<xsl:value-of select="'1'"/>
				</xsl:if>
			</xsl:variable>
			<xsl:if test="string($var126_resultof_exists) != 'false'">
				<xsl:if test="string($var128_resultof_exists) != 'false'">
					<xsl:if test="string((not($var42_resultof_logical_and) or boolean(string($var41_ReplacementValueC)))) != 'false'">
						<xsl:attribute name="ReplacementValueC_WS">
							<xsl:choose>
								<xsl:when test="string($var42_resultof_logical_and) != 'false'">
									<xsl:value-of select="string($var129_current/@ReplacementValueC)"/>
								</xsl:when>
								<xsl:otherwise>
									<xsl:value-of select="'0'"/>
								</xsl:otherwise>
							</xsl:choose>
						</xsl:attribute>
					</xsl:if>
				</xsl:if>
			</xsl:if>
			<xsl:variable name="var44_resultof_logical_and" select="((string($var129_current/@LocationPerilWind) = '1') and (string($var129_current/@LocationPerilSurge) = '1'))"/>
			<xsl:variable name="var43_ReplacementValueD">
				<xsl:if test="$var129_current/@ReplacementValueD">
					<xsl:value-of select="'1'"/>
				</xsl:if>
			</xsl:variable>
			<xsl:if test="string($var126_resultof_exists) != 'false'">
				<xsl:if test="string($var128_resultof_exists) != 'false'">
					<xsl:if test="string((not($var44_resultof_logical_and) or boolean(string($var43_ReplacementValueD)))) != 'false'">
						<xsl:attribute name="ReplacementValueD_WS">
							<xsl:choose>
								<xsl:when test="string($var44_resultof_logical_and) != 'false'">
									<xsl:value-of select="string($var129_current/@ReplacementValueD)"/>
								</xsl:when>
								<xsl:otherwise>
									<xsl:value-of select="'0'"/>
								</xsl:otherwise>
							</xsl:choose>
						</xsl:attribute>
					</xsl:if>
				</xsl:if>
			</xsl:if>
			<xsl:if test="string($var126_resultof_exists) != 'false'">
				<xsl:attribute name="LocationPerilWind">
					<xsl:value-of select="string($var129_current/@LocationPerilWind)"/>
				</xsl:attribute>
			</xsl:if>
			<xsl:if test="string($var128_resultof_exists) != 'false'">
				<xsl:attribute name="LocationPerilSurge">
					<xsl:value-of select="string($var129_current/@LocationPerilSurge)"/>
				</xsl:attribute>
			</xsl:if>
			<xsl:variable name="var45_LocationPerilSet">
				<xsl:if test="$var129_current/@LocationPerilSet">
					<xsl:value-of select="'1'"/>
				</xsl:if>
			</xsl:variable>
			<xsl:if test="string(boolean(string($var45_LocationPerilSet))) != 'false'">
				<xsl:attribute name="LocationPerilSet">
					<xsl:value-of select="string($var129_current/@LocationPerilSet)"/>
				</xsl:attribute>
			</xsl:if>
			<xsl:variable name="var46_LocLimitType">
				<xsl:if test="$var129_current/@LocLimitType">
					<xsl:value-of select="'1'"/>
				</xsl:if>
			</xsl:variable>
			<xsl:if test="string(boolean(string($var46_LocLimitType))) != 'false'">
				<xsl:attribute name="LocLimitType">
					<xsl:value-of select="string($var129_current/@LocLimitType)"/>
				</xsl:attribute>
			</xsl:if>
			<xsl:variable name="var48_resultof_logical_and" select="(('1' = string($var129_current/@LocationPerilWind)) and (string($var129_current/@LocationPerilSurge) = '0'))"/>
			<xsl:variable name="var47_Limit">
				<xsl:if test="$var129_current/@Limit1">
					<xsl:value-of select="'1'"/>
				</xsl:if>
			</xsl:variable>
			<xsl:if test="string($var126_resultof_exists) != 'false'">
				<xsl:if test="string($var128_resultof_exists) != 'false'">
					<xsl:if test="string((not($var48_resultof_logical_and) or boolean(string($var47_Limit)))) != 'false'">
						<xsl:attribute name="Limit1_W">
							<xsl:choose>
								<xsl:when test="string($var48_resultof_logical_and) != 'false'">
									<xsl:value-of select="string($var129_current/@Limit1)"/>
								</xsl:when>
								<xsl:otherwise>
									<xsl:value-of select="'0'"/>
								</xsl:otherwise>
							</xsl:choose>
						</xsl:attribute>
					</xsl:if>
				</xsl:if>
			</xsl:if>
			<xsl:variable name="var50_resultof_logical_and" select="(('1' = string($var129_current/@LocationPerilWind)) and (string($var129_current/@LocationPerilSurge) = '0'))"/>
			<xsl:variable name="var49_Limit">
				<xsl:if test="$var129_current/@Limit2">
					<xsl:value-of select="'1'"/>
				</xsl:if>
			</xsl:variable>
			<xsl:if test="string($var126_resultof_exists) != 'false'">
				<xsl:if test="string($var128_resultof_exists) != 'false'">
					<xsl:if test="string((not($var50_resultof_logical_and) or boolean(string($var49_Limit)))) != 'false'">
						<xsl:attribute name="Limit2_W">
							<xsl:choose>
								<xsl:when test="string($var50_resultof_logical_and) != 'false'">
									<xsl:value-of select="string($var129_current/@Limit2)"/>
								</xsl:when>
								<xsl:otherwise>
									<xsl:value-of select="'0'"/>
								</xsl:otherwise>
							</xsl:choose>
						</xsl:attribute>
					</xsl:if>
				</xsl:if>
			</xsl:if>
			<xsl:variable name="var52_resultof_logical_and" select="(('1' = string($var129_current/@LocationPerilWind)) and (string($var129_current/@LocationPerilSurge) = '0'))"/>
			<xsl:variable name="var51_Limit">
				<xsl:if test="$var129_current/@Limit3">
					<xsl:value-of select="'1'"/>
				</xsl:if>
			</xsl:variable>
			<xsl:if test="string($var126_resultof_exists) != 'false'">
				<xsl:if test="string($var128_resultof_exists) != 'false'">
					<xsl:if test="string((not($var52_resultof_logical_and) or boolean(string($var51_Limit)))) != 'false'">
						<xsl:attribute name="Limit3_W">
							<xsl:choose>
								<xsl:when test="string($var52_resultof_logical_and) != 'false'">
									<xsl:value-of select="string($var129_current/@Limit3)"/>
								</xsl:when>
								<xsl:otherwise>
									<xsl:value-of select="'0'"/>
								</xsl:otherwise>
							</xsl:choose>
						</xsl:attribute>
					</xsl:if>
				</xsl:if>
			</xsl:if>
			<xsl:variable name="var54_resultof_logical_and" select="(('1' = string($var129_current/@LocationPerilWind)) and (string($var129_current/@LocationPerilSurge) = '0'))"/>
			<xsl:variable name="var53_Limit">
				<xsl:if test="$var129_current/@Limit4">
					<xsl:value-of select="'1'"/>
				</xsl:if>
			</xsl:variable>
			<xsl:if test="string($var126_resultof_exists) != 'false'">
				<xsl:if test="string($var128_resultof_exists) != 'false'">
					<xsl:if test="string((not($var54_resultof_logical_and) or boolean(string($var53_Limit)))) != 'false'">
						<xsl:attribute name="Limit4_W">
							<xsl:choose>
								<xsl:when test="string($var54_resultof_logical_and) != 'false'">
									<xsl:value-of select="string($var129_current/@Limit4)"/>
								</xsl:when>
								<xsl:otherwise>
									<xsl:value-of select="'0'"/>
								</xsl:otherwise>
							</xsl:choose>
						</xsl:attribute>
					</xsl:if>
				</xsl:if>
			</xsl:if>
			<xsl:variable name="var56_resultof_logical_and" select="((string($var129_current/@LocationPerilWind) = '0') and (string($var129_current/@LocationPerilSurge) = '1'))"/>
			<xsl:variable name="var55_Limit">
				<xsl:if test="$var129_current/@Limit1">
					<xsl:value-of select="'1'"/>
				</xsl:if>
			</xsl:variable>
			<xsl:if test="string($var126_resultof_exists) != 'false'">
				<xsl:if test="string($var128_resultof_exists) != 'false'">
					<xsl:if test="string((not($var56_resultof_logical_and) or boolean(string($var55_Limit)))) != 'false'">
						<xsl:attribute name="Limit1_S">
							<xsl:choose>
								<xsl:when test="string($var56_resultof_logical_and) != 'false'">
									<xsl:value-of select="string($var129_current/@Limit1)"/>
								</xsl:when>
								<xsl:otherwise>
									<xsl:value-of select="'0'"/>
								</xsl:otherwise>
							</xsl:choose>
						</xsl:attribute>
					</xsl:if>
				</xsl:if>
			</xsl:if>
			<xsl:variable name="var58_resultof_logical_and" select="((string($var129_current/@LocationPerilWind) = '0') and (string($var129_current/@LocationPerilSurge) = '1'))"/>
			<xsl:variable name="var57_Limit">
				<xsl:if test="$var129_current/@Limit2">
					<xsl:value-of select="'1'"/>
				</xsl:if>
			</xsl:variable>
			<xsl:if test="string($var126_resultof_exists) != 'false'">
				<xsl:if test="string($var128_resultof_exists) != 'false'">
					<xsl:if test="string((not($var58_resultof_logical_and) or boolean(string($var57_Limit)))) != 'false'">
						<xsl:attribute name="Limit2_S">
							<xsl:choose>
								<xsl:when test="string($var58_resultof_logical_and) != 'false'">
									<xsl:value-of select="string($var129_current/@Limit2)"/>
								</xsl:when>
								<xsl:otherwise>
									<xsl:value-of select="'0'"/>
								</xsl:otherwise>
							</xsl:choose>
						</xsl:attribute>
					</xsl:if>
				</xsl:if>
			</xsl:if>
			<xsl:variable name="var60_resultof_logical_and" select="((string($var129_current/@LocationPerilWind) = '0') and (string($var129_current/@LocationPerilSurge) = '1'))"/>
			<xsl:variable name="var59_Limit">
				<xsl:if test="$var129_current/@Limit3">
					<xsl:value-of select="'1'"/>
				</xsl:if>
			</xsl:variable>
			<xsl:if test="string($var126_resultof_exists) != 'false'">
				<xsl:if test="string($var128_resultof_exists) != 'false'">
					<xsl:if test="string((not($var60_resultof_logical_and) or boolean(string($var59_Limit)))) != 'false'">
						<xsl:attribute name="Limit3_S">
							<xsl:choose>
								<xsl:when test="string($var60_resultof_logical_and) != 'false'">
									<xsl:value-of select="string($var129_current/@Limit3)"/>
								</xsl:when>
								<xsl:otherwise>
									<xsl:value-of select="'0'"/>
								</xsl:otherwise>
							</xsl:choose>
						</xsl:attribute>
					</xsl:if>
				</xsl:if>
			</xsl:if>
			<xsl:variable name="var62_resultof_logical_and" select="((string($var129_current/@LocationPerilWind) = '0') and (string($var129_current/@LocationPerilSurge) = '1'))"/>
			<xsl:variable name="var61_Limit">
				<xsl:if test="$var129_current/@Limit4">
					<xsl:value-of select="'1'"/>
				</xsl:if>
			</xsl:variable>
			<xsl:if test="string($var126_resultof_exists) != 'false'">
				<xsl:if test="string($var128_resultof_exists) != 'false'">
					<xsl:if test="string((not($var62_resultof_logical_and) or boolean(string($var61_Limit)))) != 'false'">
						<xsl:attribute name="Limit4_S">
							<xsl:choose>
								<xsl:when test="string($var62_resultof_logical_and) != 'false'">
									<xsl:value-of select="string($var129_current/@Limit4)"/>
								</xsl:when>
								<xsl:otherwise>
									<xsl:value-of select="'0'"/>
								</xsl:otherwise>
							</xsl:choose>
						</xsl:attribute>
					</xsl:if>
				</xsl:if>
			</xsl:if>
			<xsl:variable name="var64_resultof_logical_and" select="((string($var129_current/@LocationPerilWind) = '1') and (string($var129_current/@LocationPerilSurge) = '1'))"/>
			<xsl:variable name="var63_Limit">
				<xsl:if test="$var129_current/@Limit1">
					<xsl:value-of select="'1'"/>
				</xsl:if>
			</xsl:variable>
			<xsl:if test="string($var126_resultof_exists) != 'false'">
				<xsl:if test="string($var128_resultof_exists) != 'false'">
					<xsl:if test="string((not($var64_resultof_logical_and) or boolean(string($var63_Limit)))) != 'false'">
						<xsl:attribute name="Limit1_WS">
							<xsl:choose>
								<xsl:when test="string($var64_resultof_logical_and) != 'false'">
									<xsl:value-of select="string($var129_current/@Limit1)"/>
								</xsl:when>
								<xsl:otherwise>
									<xsl:value-of select="'0'"/>
								</xsl:otherwise>
							</xsl:choose>
						</xsl:attribute>
					</xsl:if>
				</xsl:if>
			</xsl:if>
			<xsl:variable name="var66_resultof_logical_and" select="((string($var129_current/@LocationPerilWind) = '1') and (string($var129_current/@LocationPerilSurge) = '1'))"/>
			<xsl:variable name="var65_Limit">
				<xsl:if test="$var129_current/@Limit2">
					<xsl:value-of select="'1'"/>
				</xsl:if>
			</xsl:variable>
			<xsl:if test="string($var126_resultof_exists) != 'false'">
				<xsl:if test="string($var128_resultof_exists) != 'false'">
					<xsl:if test="string((not($var66_resultof_logical_and) or boolean(string($var65_Limit)))) != 'false'">
						<xsl:attribute name="Limit2_WS">
							<xsl:choose>
								<xsl:when test="string($var66_resultof_logical_and) != 'false'">
									<xsl:value-of select="string($var129_current/@Limit2)"/>
								</xsl:when>
								<xsl:otherwise>
									<xsl:value-of select="'0'"/>
								</xsl:otherwise>
							</xsl:choose>
						</xsl:attribute>
					</xsl:if>
				</xsl:if>
			</xsl:if>
			<xsl:variable name="var68_resultof_logical_and" select="((string($var129_current/@LocationPerilWind) = '1') and (string($var129_current/@LocationPerilSurge) = '1'))"/>
			<xsl:variable name="var67_Limit">
				<xsl:if test="$var129_current/@Limit3">
					<xsl:value-of select="'1'"/>
				</xsl:if>
			</xsl:variable>
			<xsl:if test="string($var126_resultof_exists) != 'false'">
				<xsl:if test="string($var128_resultof_exists) != 'false'">
					<xsl:if test="string((not($var68_resultof_logical_and) or boolean(string($var67_Limit)))) != 'false'">
						<xsl:attribute name="Limit3_WS">
							<xsl:choose>
								<xsl:when test="string($var68_resultof_logical_and) != 'false'">
									<xsl:value-of select="string($var129_current/@Limit3)"/>
								</xsl:when>
								<xsl:otherwise>
									<xsl:value-of select="'0'"/>
								</xsl:otherwise>
							</xsl:choose>
						</xsl:attribute>
					</xsl:if>
				</xsl:if>
			</xsl:if>
			<xsl:variable name="var70_resultof_logical_and" select="((string($var129_current/@LocationPerilWind) = '1') and (string($var129_current/@LocationPerilSurge) = '1'))"/>
			<xsl:variable name="var69_Limit">
				<xsl:if test="$var129_current/@Limit4">
					<xsl:value-of select="'1'"/>
				</xsl:if>
			</xsl:variable>
			<xsl:if test="string($var126_resultof_exists) != 'false'">
				<xsl:if test="string($var128_resultof_exists) != 'false'">
					<xsl:if test="string((not($var70_resultof_logical_and) or boolean(string($var69_Limit)))) != 'false'">
						<xsl:attribute name="Limit4_WS">
							<xsl:choose>
								<xsl:when test="string($var70_resultof_logical_and) != 'false'">
									<xsl:value-of select="string($var129_current/@Limit4)"/>
								</xsl:when>
								<xsl:otherwise>
									<xsl:value-of select="'0'"/>
								</xsl:otherwise>
							</xsl:choose>
						</xsl:attribute>
					</xsl:if>
				</xsl:if>
			</xsl:if>
			<xsl:variable name="var71_LocDedType">
				<xsl:if test="$var129_current/@LocDedType">
					<xsl:value-of select="'1'"/>
				</xsl:if>
			</xsl:variable>
			<xsl:if test="string(boolean(string($var71_LocDedType))) != 'false'">
				<xsl:attribute name="LocDedType">
					<xsl:value-of select="string($var129_current/@LocDedType)"/>
				</xsl:attribute>
			</xsl:if>
			<xsl:variable name="var73_resultof_logical_and" select="(('1' = string($var129_current/@LocationPerilWind)) and (string($var129_current/@LocationPerilSurge) = '0'))"/>
			<xsl:variable name="var72_Deductible">
				<xsl:if test="$var129_current/@Deductible1">
					<xsl:value-of select="'1'"/>
				</xsl:if>
			</xsl:variable>
			<xsl:if test="string($var126_resultof_exists) != 'false'">
				<xsl:if test="string($var128_resultof_exists) != 'false'">
					<xsl:if test="string((not($var73_resultof_logical_and) or boolean(string($var72_Deductible)))) != 'false'">
						<xsl:attribute name="Deductible1_W">
							<xsl:choose>
								<xsl:when test="string($var73_resultof_logical_and) != 'false'">
									<xsl:value-of select="string($var129_current/@Deductible1)"/>
								</xsl:when>
								<xsl:otherwise>
									<xsl:value-of select="'0'"/>
								</xsl:otherwise>
							</xsl:choose>
						</xsl:attribute>
					</xsl:if>
				</xsl:if>
			</xsl:if>
			<xsl:variable name="var75_resultof_logical_and" select="(('1' = string($var129_current/@LocationPerilWind)) and (string($var129_current/@LocationPerilSurge) = '0'))"/>
			<xsl:variable name="var74_Deductible">
				<xsl:if test="$var129_current/@Deductible2">
					<xsl:value-of select="'1'"/>
				</xsl:if>
			</xsl:variable>
			<xsl:if test="string($var126_resultof_exists) != 'false'">
				<xsl:if test="string($var128_resultof_exists) != 'false'">
					<xsl:if test="string((not($var75_resultof_logical_and) or boolean(string($var74_Deductible)))) != 'false'">
						<xsl:attribute name="Deductible2_W">
							<xsl:choose>
								<xsl:when test="string($var75_resultof_logical_and) != 'false'">
									<xsl:value-of select="string($var129_current/@Deductible2)"/>
								</xsl:when>
								<xsl:otherwise>
									<xsl:value-of select="'0'"/>
								</xsl:otherwise>
							</xsl:choose>
						</xsl:attribute>
					</xsl:if>
				</xsl:if>
			</xsl:if>
			<xsl:variable name="var77_resultof_logical_and" select="(('1' = string($var129_current/@LocationPerilWind)) and (string($var129_current/@LocationPerilSurge) = '0'))"/>
			<xsl:variable name="var76_Deductible">
				<xsl:if test="$var129_current/@Deductible3">
					<xsl:value-of select="'1'"/>
				</xsl:if>
			</xsl:variable>
			<xsl:if test="string($var126_resultof_exists) != 'false'">
				<xsl:if test="string($var128_resultof_exists) != 'false'">
					<xsl:if test="string((not($var77_resultof_logical_and) or boolean(string($var76_Deductible)))) != 'false'">
						<xsl:attribute name="Deductible3_W">
							<xsl:choose>
								<xsl:when test="string($var77_resultof_logical_and) != 'false'">
									<xsl:value-of select="string($var129_current/@Deductible3)"/>
								</xsl:when>
								<xsl:otherwise>
									<xsl:value-of select="'0'"/>
								</xsl:otherwise>
							</xsl:choose>
						</xsl:attribute>
					</xsl:if>
				</xsl:if>
			</xsl:if>
			<xsl:variable name="var79_resultof_logical_and" select="(('1' = string($var129_current/@LocationPerilWind)) and (string($var129_current/@LocationPerilSurge) = '0'))"/>
			<xsl:variable name="var78_Deductible">
				<xsl:if test="$var129_current/@Deductible4">
					<xsl:value-of select="'1'"/>
				</xsl:if>
			</xsl:variable>
			<xsl:if test="string($var126_resultof_exists) != 'false'">
				<xsl:if test="string($var128_resultof_exists) != 'false'">
					<xsl:if test="string((not($var79_resultof_logical_and) or boolean(string($var78_Deductible)))) != 'false'">
						<xsl:attribute name="Deductible4_W">
							<xsl:choose>
								<xsl:when test="string($var79_resultof_logical_and) != 'false'">
									<xsl:value-of select="string($var129_current/@Deductible4)"/>
								</xsl:when>
								<xsl:otherwise>
									<xsl:value-of select="'0'"/>
								</xsl:otherwise>
							</xsl:choose>
						</xsl:attribute>
					</xsl:if>
				</xsl:if>
			</xsl:if>
			<xsl:variable name="var81_resultof_logical_and" select="((string($var129_current/@LocationPerilWind) = '0') and (string($var129_current/@LocationPerilSurge) = '1'))"/>
			<xsl:variable name="var80_Deductible">
				<xsl:if test="$var129_current/@Deductible1">
					<xsl:value-of select="'1'"/>
				</xsl:if>
			</xsl:variable>
			<xsl:if test="string($var126_resultof_exists) != 'false'">
				<xsl:if test="string($var128_resultof_exists) != 'false'">
					<xsl:if test="string((not($var81_resultof_logical_and) or boolean(string($var80_Deductible)))) != 'false'">
						<xsl:attribute name="Deductible1_S">
							<xsl:choose>
								<xsl:when test="string($var81_resultof_logical_and) != 'false'">
									<xsl:value-of select="string($var129_current/@Deductible1)"/>
								</xsl:when>
								<xsl:otherwise>
									<xsl:value-of select="'0'"/>
								</xsl:otherwise>
							</xsl:choose>
						</xsl:attribute>
					</xsl:if>
				</xsl:if>
			</xsl:if>
			<xsl:variable name="var83_resultof_logical_and" select="((string($var129_current/@LocationPerilWind) = '0') and (string($var129_current/@LocationPerilSurge) = '1'))"/>
			<xsl:variable name="var82_Deductible">
				<xsl:if test="$var129_current/@Deductible2">
					<xsl:value-of select="'1'"/>
				</xsl:if>
			</xsl:variable>
			<xsl:if test="string($var126_resultof_exists) != 'false'">
				<xsl:if test="string($var128_resultof_exists) != 'false'">
					<xsl:if test="string((not($var83_resultof_logical_and) or boolean(string($var82_Deductible)))) != 'false'">
						<xsl:attribute name="Deductible2_S">
							<xsl:choose>
								<xsl:when test="string($var83_resultof_logical_and) != 'false'">
									<xsl:value-of select="string($var129_current/@Deductible2)"/>
								</xsl:when>
								<xsl:otherwise>
									<xsl:value-of select="'0'"/>
								</xsl:otherwise>
							</xsl:choose>
						</xsl:attribute>
					</xsl:if>
				</xsl:if>
			</xsl:if>
			<xsl:variable name="var85_resultof_logical_and" select="((string($var129_current/@LocationPerilWind) = '0') and (string($var129_current/@LocationPerilSurge) = '1'))"/>
			<xsl:variable name="var84_Deductible">
				<xsl:if test="$var129_current/@Deductible3">
					<xsl:value-of select="'1'"/>
				</xsl:if>
			</xsl:variable>
			<xsl:if test="string($var126_resultof_exists) != 'false'">
				<xsl:if test="string($var128_resultof_exists) != 'false'">
					<xsl:if test="string((not($var85_resultof_logical_and) or boolean(string($var84_Deductible)))) != 'false'">
						<xsl:attribute name="Deductible3_S">
							<xsl:choose>
								<xsl:when test="string($var85_resultof_logical_and) != 'false'">
									<xsl:value-of select="string($var129_current/@Deductible3)"/>
								</xsl:when>
								<xsl:otherwise>
									<xsl:value-of select="'0'"/>
								</xsl:otherwise>
							</xsl:choose>
						</xsl:attribute>
					</xsl:if>
				</xsl:if>
			</xsl:if>
			<xsl:variable name="var87_resultof_logical_and" select="((string($var129_current/@LocationPerilWind) = '0') and (string($var129_current/@LocationPerilSurge) = '1'))"/>
			<xsl:variable name="var86_Deductible">
				<xsl:if test="$var129_current/@Deductible4">
					<xsl:value-of select="'1'"/>
				</xsl:if>
			</xsl:variable>
			<xsl:if test="string($var126_resultof_exists) != 'false'">
				<xsl:if test="string($var128_resultof_exists) != 'false'">
					<xsl:if test="string((not($var87_resultof_logical_and) or boolean(string($var86_Deductible)))) != 'false'">
						<xsl:attribute name="Deductible4_S">
							<xsl:choose>
								<xsl:when test="string($var87_resultof_logical_and) != 'false'">
									<xsl:value-of select="string($var129_current/@Deductible4)"/>
								</xsl:when>
								<xsl:otherwise>
									<xsl:value-of select="'0'"/>
								</xsl:otherwise>
							</xsl:choose>
						</xsl:attribute>
					</xsl:if>
				</xsl:if>
			</xsl:if>
			<xsl:variable name="var89_resultof_logical_and" select="((string($var129_current/@LocationPerilWind) = '1') and (string($var129_current/@LocationPerilSurge) = '1'))"/>
			<xsl:variable name="var88_Deductible">
				<xsl:if test="$var129_current/@Deductible1">
					<xsl:value-of select="'1'"/>
				</xsl:if>
			</xsl:variable>
			<xsl:if test="string($var126_resultof_exists) != 'false'">
				<xsl:if test="string($var128_resultof_exists) != 'false'">
					<xsl:if test="string((not($var89_resultof_logical_and) or boolean(string($var88_Deductible)))) != 'false'">
						<xsl:attribute name="Deductible1_WS">
							<xsl:choose>
								<xsl:when test="string($var89_resultof_logical_and) != 'false'">
									<xsl:value-of select="string($var129_current/@Deductible1)"/>
								</xsl:when>
								<xsl:otherwise>
									<xsl:value-of select="'0'"/>
								</xsl:otherwise>
							</xsl:choose>
						</xsl:attribute>
					</xsl:if>
				</xsl:if>
			</xsl:if>
			<xsl:variable name="var91_resultof_logical_and" select="((string($var129_current/@LocationPerilWind) = '1') and (string($var129_current/@LocationPerilSurge) = '1'))"/>
			<xsl:variable name="var90_Deductible">
				<xsl:if test="$var129_current/@Deductible2">
					<xsl:value-of select="'1'"/>
				</xsl:if>
			</xsl:variable>
			<xsl:if test="string($var126_resultof_exists) != 'false'">
				<xsl:if test="string($var128_resultof_exists) != 'false'">
					<xsl:if test="string((not($var91_resultof_logical_and) or boolean(string($var90_Deductible)))) != 'false'">
						<xsl:attribute name="Deductible2_WS">
							<xsl:choose>
								<xsl:when test="string($var91_resultof_logical_and) != 'false'">
									<xsl:value-of select="string($var129_current/@Deductible2)"/>
								</xsl:when>
								<xsl:otherwise>
									<xsl:value-of select="'0'"/>
								</xsl:otherwise>
							</xsl:choose>
						</xsl:attribute>
					</xsl:if>
				</xsl:if>
			</xsl:if>
			<xsl:variable name="var93_resultof_logical_and" select="((string($var129_current/@LocationPerilWind) = '1') and (string($var129_current/@LocationPerilSurge) = '1'))"/>
			<xsl:variable name="var92_Deductible">
				<xsl:if test="$var129_current/@Deductible3">
					<xsl:value-of select="'1'"/>
				</xsl:if>
			</xsl:variable>
			<xsl:if test="string($var126_resultof_exists) != 'false'">
				<xsl:if test="string($var128_resultof_exists) != 'false'">
					<xsl:if test="string((not($var93_resultof_logical_and) or boolean(string($var92_Deductible)))) != 'false'">
						<xsl:attribute name="Deductible3_WS">
							<xsl:choose>
								<xsl:when test="string($var93_resultof_logical_and) != 'false'">
									<xsl:value-of select="string($var129_current/@Deductible3)"/>
								</xsl:when>
								<xsl:otherwise>
									<xsl:value-of select="'0'"/>
								</xsl:otherwise>
							</xsl:choose>
						</xsl:attribute>
					</xsl:if>
				</xsl:if>
			</xsl:if>
			<xsl:variable name="var95_resultof_logical_and" select="((string($var129_current/@LocationPerilWind) = '1') and (string($var129_current/@LocationPerilSurge) = '1'))"/>
			<xsl:variable name="var94_Deductible">
				<xsl:if test="$var129_current/@Deductible4">
					<xsl:value-of select="'1'"/>
				</xsl:if>
			</xsl:variable>
			<xsl:if test="string($var126_resultof_exists) != 'false'">
				<xsl:if test="string($var128_resultof_exists) != 'false'">
					<xsl:if test="string((not($var95_resultof_logical_and) or boolean(string($var94_Deductible)))) != 'false'">
						<xsl:attribute name="Deductible4_WS">
							<xsl:choose>
								<xsl:when test="string($var95_resultof_logical_and) != 'false'">
									<xsl:value-of select="string($var129_current/@Deductible4)"/>
								</xsl:when>
								<xsl:otherwise>
									<xsl:value-of select="'0'"/>
								</xsl:otherwise>
							</xsl:choose>
						</xsl:attribute>
					</xsl:if>
				</xsl:if>
			</xsl:if>
			<xsl:variable name="var96_Participation">
				<xsl:if test="$var129_current/@Participation1">
					<xsl:value-of select="'1'"/>
				</xsl:if>
			</xsl:variable>
			<xsl:if test="string(boolean(string($var96_Participation))) != 'false'">
				<xsl:attribute name="Participation1">
					<xsl:value-of select="string($var129_current/@Participation1)"/>
				</xsl:attribute>
			</xsl:if>
			<xsl:variable name="var97_Participation">
				<xsl:if test="$var129_current/@Participation2">
					<xsl:value-of select="'1'"/>
				</xsl:if>
			</xsl:variable>
			<xsl:if test="string(boolean(string($var97_Participation))) != 'false'">
				<xsl:attribute name="Participation2">
					<xsl:value-of select="string($var129_current/@Participation2)"/>
				</xsl:attribute>
			</xsl:if>
			<xsl:variable name="var98_SubLimitPerilWind">
				<xsl:if test="$var129_current/@SubLimitPerilWind">
					<xsl:value-of select="'1'"/>
				</xsl:if>
			</xsl:variable>
			<xsl:if test="string(boolean(string($var98_SubLimitPerilWind))) != 'false'">
				<xsl:attribute name="SubLimitPerilWind">
					<xsl:value-of select="string($var129_current/@SubLimitPerilWind)"/>
				</xsl:attribute>
			</xsl:if>
			<xsl:variable name="var99_SubLimitPerilSurge">
				<xsl:if test="$var129_current/@SubLimitPerilSurge">
					<xsl:value-of select="'1'"/>
				</xsl:if>
			</xsl:variable>
			<xsl:if test="string(boolean(string($var99_SubLimitPerilSurge))) != 'false'">
				<xsl:attribute name="SubLimitPerilSurge">
					<xsl:value-of select="string($var129_current/@SubLimitPerilSurge)"/>
				</xsl:attribute>
			</xsl:if>
			<xsl:variable name="var100_ConditionType">
				<xsl:if test="$var129_current/@ConditionType">
					<xsl:value-of select="'1'"/>
				</xsl:if>
			</xsl:variable>
			<xsl:if test="string(boolean(string($var100_ConditionType))) != 'false'">
				<xsl:attribute name="ConditionType">
					<xsl:value-of select="string($var129_current/@ConditionType)"/>
				</xsl:attribute>
			</xsl:if>
			<xsl:variable name="var101_SublimitFlag">
				<xsl:if test="$var129_current/@SublimitFlag">
					<xsl:value-of select="'1'"/>
				</xsl:if>
			</xsl:variable>
			<xsl:if test="string(boolean(string($var101_SublimitFlag))) != 'false'">
				<xsl:attribute name="SublimitFlag">
					<xsl:value-of select="string($var129_current/@SublimitFlag)"/>
				</xsl:attribute>
			</xsl:if>
			<xsl:variable name="var102_SublimitLimitType">
				<xsl:if test="$var129_current/@SublimitLimit1Type">
					<xsl:value-of select="'1'"/>
				</xsl:if>
			</xsl:variable>
			<xsl:if test="string(boolean(string($var102_SublimitLimitType))) != 'false'">
				<xsl:attribute name="SublimitLimit1Type">
					<xsl:value-of select="string($var129_current/@SublimitLimit1Type)"/>
				</xsl:attribute>
			</xsl:if>
			<xsl:variable name="var103_ContractCurrency">
				<xsl:if test="$var129_current/@ContractCurrency">
					<xsl:value-of select="'1'"/>
				</xsl:if>
			</xsl:variable>
			<xsl:if test="string(boolean(string($var103_ContractCurrency))) != 'false'">
				<xsl:attribute name="ContractCurrency">
					<xsl:value-of select="string($var129_current/@ContractCurrency)"/>
				</xsl:attribute>
			</xsl:if>
			<xsl:variable name="var104_sublimitLimit">
				<xsl:if test="$var129_current/@sublimitLimit1">
					<xsl:value-of select="'1'"/>
				</xsl:if>
			</xsl:variable>
			<xsl:if test="string(boolean(string($var104_sublimitLimit))) != 'false'">
				<xsl:attribute name="sublimitLimit1">
					<xsl:value-of select="string($var129_current/@sublimitLimit1)"/>
				</xsl:attribute>
			</xsl:if>
			<xsl:variable name="var105_sublimitLimit">
				<xsl:if test="$var129_current/@sublimitLimit2">
					<xsl:value-of select="'1'"/>
				</xsl:if>
			</xsl:variable>
			<xsl:if test="string(boolean(string($var105_sublimitLimit))) != 'false'">
				<xsl:attribute name="sublimitLimit2">
					<xsl:value-of select="string($var129_current/@sublimitLimit2)"/>
				</xsl:attribute>
			</xsl:if>
			<xsl:variable name="var106_sublimitLimit">
				<xsl:if test="$var129_current/@sublimitLimit3">
					<xsl:value-of select="'1'"/>
				</xsl:if>
			</xsl:variable>
			<xsl:if test="string(boolean(string($var106_sublimitLimit))) != 'false'">
				<xsl:attribute name="sublimitLimit3">
					<xsl:value-of select="string($var129_current/@sublimitLimit3)"/>
				</xsl:attribute>
			</xsl:if>
			<xsl:variable name="var107_sublimitLimit">
				<xsl:if test="$var129_current/@sublimitLimit4">
					<xsl:value-of select="'1'"/>
				</xsl:if>
			</xsl:variable>
			<xsl:if test="string(boolean(string($var107_sublimitLimit))) != 'false'">
				<xsl:attribute name="sublimitLimit4">
					<xsl:value-of select="string($var129_current/@sublimitLimit4)"/>
				</xsl:attribute>
			</xsl:if>
			<xsl:variable name="var108_SublimitXs">
				<xsl:if test="$var129_current/@SublimitXs1">
					<xsl:value-of select="'1'"/>
				</xsl:if>
			</xsl:variable>
			<xsl:if test="string(boolean(string($var108_SublimitXs))) != 'false'">
				<xsl:attribute name="SublimitXs1">
					<xsl:value-of select="string($var129_current/@SublimitXs1)"/>
				</xsl:attribute>
			</xsl:if>
			<xsl:variable name="var109_SublimitXs">
				<xsl:if test="$var129_current/@SublimitXs2">
					<xsl:value-of select="'1'"/>
				</xsl:if>
			</xsl:variable>
			<xsl:if test="string(boolean(string($var109_SublimitXs))) != 'false'">
				<xsl:attribute name="SublimitXs2">
					<xsl:value-of select="string($var129_current/@SublimitXs2)"/>
				</xsl:attribute>
			</xsl:if>
			<xsl:variable name="var110_SublimitXs">
				<xsl:if test="$var129_current/@SublimitXs3">
					<xsl:value-of select="'1'"/>
				</xsl:if>
			</xsl:variable>
			<xsl:if test="string(boolean(string($var110_SublimitXs))) != 'false'">
				<xsl:attribute name="SublimitXs3">
					<xsl:value-of select="string($var129_current/@SublimitXs3)"/>
				</xsl:attribute>
			</xsl:if>
			<xsl:variable name="var111_SublimitXs">
				<xsl:if test="$var129_current/@SublimitXs4">
					<xsl:value-of select="'1'"/>
				</xsl:if>
			</xsl:variable>
			<xsl:if test="string(boolean(string($var111_SublimitXs))) != 'false'">
				<xsl:attribute name="SublimitXs4">
					<xsl:value-of select="string($var129_current/@SublimitXs4)"/>
				</xsl:attribute>
			</xsl:if>
			<xsl:variable name="var112_SublimitDedType">
				<xsl:if test="$var129_current/@SublimitDedType">
					<xsl:value-of select="'1'"/>
				</xsl:if>
			</xsl:variable>
			<xsl:if test="string(boolean(string($var112_SublimitDedType))) != 'false'">
				<xsl:attribute name="SublimitDedType">
					<xsl:value-of select="string($var129_current/@SublimitDedType)"/>
				</xsl:attribute>
			</xsl:if>
			<xsl:variable name="var113_SublimitDed">
				<xsl:if test="$var129_current/@SublimitDed1">
					<xsl:value-of select="'1'"/>
				</xsl:if>
			</xsl:variable>
			<xsl:if test="string(boolean(string($var113_SublimitDed))) != 'false'">
				<xsl:attribute name="SublimitDed1">
					<xsl:value-of select="string($var129_current/@SublimitDed1)"/>
				</xsl:attribute>
			</xsl:if>
			<xsl:variable name="var114_SublimitDed">
				<xsl:if test="$var129_current/@SublimitDed2">
					<xsl:value-of select="'1'"/>
				</xsl:if>
			</xsl:variable>
			<xsl:if test="string(boolean(string($var114_SublimitDed))) != 'false'">
				<xsl:attribute name="SublimitDed2">
					<xsl:value-of select="string($var129_current/@SublimitDed2)"/>
				</xsl:attribute>
			</xsl:if>
			<xsl:variable name="var115_RoofAnchorageCode">
				<xsl:if test="$var129_current/@RoofAnchorageCode">
					<xsl:value-of select="'1'"/>
				</xsl:if>
			</xsl:variable>
			<xsl:if test="string(boolean(string($var115_RoofAnchorageCode))) != 'false'">
				<xsl:attribute name="RoofAnchorageCode">
					<xsl:value-of select="string($var129_current/@RoofAnchorageCode)"/>
				</xsl:attribute>
			</xsl:if>
			<xsl:variable name="var116_RoofAttachedStructureCode">
				<xsl:if test="$var129_current/@RoofAttachedStructureCode">
					<xsl:value-of select="'1'"/>
				</xsl:if>
			</xsl:variable>
			<xsl:if test="string(boolean(string($var116_RoofAttachedStructureCode))) != 'false'">
				<xsl:attribute name="RoofAttachedStructureCode">
					<xsl:value-of select="string($var129_current/@RoofAttachedStructureCode)"/>
				</xsl:attribute>
			</xsl:if>
			<xsl:variable name="var117_RoofCoverAttachCode">
				<xsl:if test="$var129_current/@RoofCoverAttachCode">
					<xsl:value-of select="'1'"/>
				</xsl:if>
			</xsl:variable>
			<xsl:if test="string(boolean(string($var117_RoofCoverAttachCode))) != 'false'">
				<xsl:attribute name="RoofCoverAttachCode">
					<xsl:value-of select="string($var129_current/@RoofCoverAttachCode)"/>
				</xsl:attribute>
			</xsl:if>
			<xsl:variable name="var118_RoofCoverCode">
				<xsl:if test="$var129_current/@RoofCoverCode">
					<xsl:value-of select="'1'"/>
				</xsl:if>
			</xsl:variable>
			<xsl:if test="string(boolean(string($var118_RoofCoverCode))) != 'false'">
				<xsl:attribute name="RoofCoverCode">
					<xsl:value-of select="string($var129_current/@RoofCoverCode)"/>
				</xsl:attribute>
			</xsl:if>
			<xsl:variable name="var119_RoofDeckAttachCode">
				<xsl:if test="$var129_current/@RoofDeckAttachCode">
					<xsl:value-of select="'1'"/>
				</xsl:if>
			</xsl:variable>
			<xsl:if test="string(boolean(string($var119_RoofDeckAttachCode))) != 'false'">
				<xsl:attribute name="RoofDeckAttachCode">
					<xsl:value-of select="string($var129_current/@RoofDeckAttachCode)"/>
				</xsl:attribute>
			</xsl:if>
			<xsl:variable name="var120_RoofDeckCode">
				<xsl:if test="$var129_current/@RoofDeckCode">
					<xsl:value-of select="'1'"/>
				</xsl:if>
			</xsl:variable>
			<xsl:if test="string(boolean(string($var120_RoofDeckCode))) != 'false'">
				<xsl:attribute name="RoofDeckCode">
					<xsl:value-of select="string($var129_current/@RoofDeckCode)"/>
				</xsl:attribute>
			</xsl:if>
			<xsl:variable name="var121_RoofGeometryCode">
				<xsl:if test="$var129_current/@RoofGeometryCode">
					<xsl:value-of select="'1'"/>
				</xsl:if>
			</xsl:variable>
			<xsl:if test="string(boolean(string($var121_RoofGeometryCode))) != 'false'">
				<xsl:attribute name="RoofGeometryCode">
					<xsl:value-of select="string($var129_current/@RoofGeometryCode)"/>
				</xsl:attribute>
			</xsl:if>
			<xsl:variable name="var122_RoofPitchCode">
				<xsl:if test="$var129_current/@RoofPitchCode">
					<xsl:value-of select="'1'"/>
				</xsl:if>
			</xsl:variable>
			<xsl:if test="string(boolean(string($var122_RoofPitchCode))) != 'false'">
				<xsl:attribute name="RoofPitchCode">
					<xsl:value-of select="string($var129_current/@RoofPitchCode)"/>
				</xsl:attribute>
			</xsl:if>
			<xsl:variable name="var123_RoofYearBuilt">
				<xsl:if test="$var129_current/@RoofYearBuilt">
					<xsl:value-of select="'1'"/>
				</xsl:if>
			</xsl:variable>
			<xsl:if test="string(boolean(string($var123_RoofYearBuilt))) != 'false'">
				<xsl:attribute name="RoofYearBuilt">
					<xsl:value-of select="string($var129_current/@RoofYearBuilt)"/>
				</xsl:attribute>
			</xsl:if>
			<xsl:variable name="var124_WindowProtectionCode">
				<xsl:if test="$var129_current/@WindowProtectionCode">
					<xsl:value-of select="'1'"/>
				</xsl:if>
			</xsl:variable>
			<xsl:if test="string(boolean(string($var124_WindowProtectionCode))) != 'false'">
				<xsl:attribute name="WindowProtectionCode">
					<xsl:value-of select="string($var129_current/@WindowProtectionCode)"/>
				</xsl:attribute>
			</xsl:if>
		</rec>
	</xsl:template>
	<xsl:template name="agt:MapToCanLocARA_A_Cede_var132_resultof_map">
		<xsl:param name="var131_current"/>
		<xsl:for-each select="$var131_current/rec">
			<xsl:call-template name="agt:MapToCanLocARA_A_Cede_var130_function">
				<xsl:with-param name="var129_current" select="."/>
			</xsl:call-template>
		</xsl:for-each>
	</xsl:template>
	<xsl:template match="/">
		<root>
			<xsl:attribute name="xsi:noNamespaceSchemaLocation" namespace="http://www.w3.org/2001/XMLSchema-instance">C:/Users/Administrator/Desktop/dbFiles/Transformations/ARA/AIR/ValidationFiles/CanLocARA_A_Cede.xsd</xsl:attribute>
			<xsl:for-each select="root">
				<xsl:call-template name="agt:MapToCanLocARA_A_Cede_var132_resultof_map">
					<xsl:with-param name="var131_current" select="."/>
				</xsl:call-template>
			</xsl:for-each>
		</root>
	</xsl:template>
</xsl:stylesheet>
